/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: "var(--primary)",
        muted: "var(--muted)",
        "muted-foreground": "var(--muted-foreground)",
        border: "var(--border)",
        ring: "var(--ring)",
        success: "var(--success)",
        "success-foreground": "var(--success-foreground)",
        "table-header": "var(--table-header)",
        "table-text": "var(--table-text)",
        "table-accent": "var(--table-accent)",
        "table-row-border": "var(--table-row-border)",
        "table-scrollbar": "var(--table-scrollbar)",
        "table-pagination-text": "var(--table-pagination-text)",
        "badge-active-bg": "var(--badge-active-bg)",
        "badge-active-text": "var(--badge-active-text)",
        "badge-pending-bg": "var(--badge-pending-bg)",
        "badge-pending-text": "var(--badge-pending-text)",
        "badge-expired-bg": "var(--badge-expired-bg)",
        "badge-expired-text": "var(--badge-expired-text)",
        "badge-blocked-bg": "var(--badge-blocked-bg)",
        "badge-blocked-text": "var(--badge-blocked-text)",
        "badge-corp-admin-bg": "var(--badge-corp-admin-bg)",
        "badge-corp-admin-text": "var(--badge-corp-admin-text)",
        "badge-company-admin-bg": "var(--badge-company-admin-bg)",
        "badge-company-admin-text": "var(--badge-company-admin-text)",
        "badge-executive-bg": "var(--badge-executive-bg)",
        "badge-executive-text": "var(--badge-executive-text)",
        "badge-success-bg": "var(--badge-success-bg)",
        "badge-success-text": "var(--badge-success-text)",
        "badge-warning-bg": "var(--badge-warning-bg)",
        "badge-warning-text": "var(--badge-warning-text)",
      },
    },
  },
  plugins: [],
};
