export const ROUTES = {
  USER_DIRECTORY: "/",
  VIEW_USER_DETAILS: "/user-details",
  VIEW_CONTACT_DETAILS: "/user-details/contact",
  FLOW_COVER: "/flow-cover",
  DASHBOARD: "/",
  CORPORATION_DIRECTORY: "/corporation-directory",
  COMPANY_DIRECTORY: "/company-directory",
  ROLES_PERMISSIONS: "/roles-permissions",
  COACHES: "/coaches",
  BILLING_MANAGEMENT: "/billing-management",
  PLANS_PRICING: "/plans-pricing",
  INVOICES: "/invoices",
  PROMO_CODE_MANAGEMENT: "/promo-code-management",
  QUESTION_BANK: "/question-bank",
  LEARNING_LIBRARY: "/learning-library",
  SYSTEM_HEALTH: "/system-health",
  SECURITY_BASELINES: "/security-baselines",
  AUDIT_LOGS: "/audit-logs",
  MAINTENANCE: "/maintenance",
  REPORTS: "/reports",
  NOTIFICATIONS: "/notifications",
  SETTINGS: "/settings",
} as const;
